USWDS - Alerts: Add alert list examples and update styles.
uswds/uswds pull request #3507
Opened 2020-06-15 14:30 UTC by mejiaj

## Description

- Moved `margin-bottom: 0` to the last item
- Removed left padding from 1st level lists
- Removed margin-top from alert lists

## Additional information

Need confirmation on : 

- Should this behave like other lists or does it need special styling?
- Do we expect users to use `.usa-list` in their alert lists?

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2020-09-08 18:16 UTC, thisisdano requested changes

2020-09-08 18:16 UTC, thisisdano commented on src/components/05-alerts/alerts.njk
> +      <li>Seeing new patients through telehealth</li>
Don't use an example tied a specific use case like telehealth

2020-09-08 18:16 UTC, thisisdano commented on src/components/05-alerts/alerts.njk
> +    <ul>
let's use `usa-list` for this content.

2020-09-08 18:16 UTC, thisisdano commented on src/components/05-alerts/alerts.njk
> +<h6>Nested .usa-list</h6>
Do these need to be separate examples?

2020-09-08 18:16 UTC, thisisdano commented on src/stylesheets/components/_alerts.scss
> +  > ul,
let's use `usa-list` classes

2020-09-09 21:13 UTC, mejiaj commented on src/components/05-alerts/alerts.njk
> +<h6>Nested .usa-list</h6>
No, it was just for testing. Removed.

2020-09-11 07:28 UTC, thisisdano commented
These long lists can and should be in some testing example, but not in the main alerts that we'd see on the website. Those should appear as they did before.

2020-09-11 18:37 UTC, thisisdano approved these changes

2020-09-11 18:47 UTC, merged