update readme to show how to use modular components in React and Angular
uswds/uswds pull request #3723
Opened 2020-10-01 13:51 UTC by sarnikbixal

<!-- Please feel free to remove whatever sections/lines in this aren’t relevant.

update readme to show how to use modular components in React and Angular

## Description

update readme to show how to use modular components in React and Angular

## Additional information

Include any of the following (as necessary): 

How do we set this on USWDS site? I am not sure if this Readme will update the same information on the uswds-site domain.

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2020-10-23 15:39 UTC, mejiaj requested changes
Some typos, otherwise LGTM.

2020-10-23 15:39 UTC, mejiaj commented on README.md
> +**If you are using am odern framework such as React/Angular you can import components and initialize it in your libraries dom ready lifecycle event.**
Typo `am odern framework`

2020-10-23 15:39 UTC, mejiaj commented on README.md
> +     // inititalize
Typo on `initialize`

2020-10-23 15:39 UTC, mejiaj commented on README.md
> +     characterCount.on(ref); // default ref is document.body, if you want to use default you do not bave to pass arguments
Typo `default you do not bave to pass arguments`

2020-10-23 15:39 UTC, mejiaj commented on README.md
> +    this.ref = document.body; // default ref is document.body, if you want to use default you do not bave to pass arguments
Typo `you do not bave to pass arguments`

2020-10-23 15:39 UTC, mejiaj commented on README.md
> +    // inititalize
Typo ` // inititalize`

2020-10-30 16:04 UTC, sarnikbixal reviewed
fixed typos

2020-10-30 16:09 UTC, mejiaj approved these changes

2020-11-23 05:57 UTC, merged