Rebuild components to make uswds-site more accessible
uswds/uswds pull request #4056
Opened 2021-03-01 09:23 UTC by thisisdano

2021-03-01 09:34 UTC, thisisdano commented on src/components/_uswds-form.njk
> +      {{ yield | safe }}
Added a form template to prevent having to wrap form controls in a `form` element

2021-03-01 09:34 UTC, thisisdano commented on src/components/accordion/accordion.njk
> +      <h4 class="usa-accordion__heading">
All changes like this are to address heading order on uswds-site

2021-03-01 17:24 UTC, mejiaj requested changes
Margins are gone on [Character Count NEW](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/dw-remove-preview-heds/components/detail/character-count.html) vs [Character Count DEV](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/components/detail/character-count.html)

And [Card Compare](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/dw-remove-preview-heds/components/detail/card--compare.html) seems to be missing some grid classes

Do we need to apply this new Form template to the following?
- [Checkbox tile](https://github.com/uswds/uswds/blob/dw-remove-preview-heds/src/components/checkbox/checkbox--tile.njk#L1)
- [Radio tile](https://github.com/uswds/uswds/blob/dw-remove-preview-heds/src/components/radio-buttons/radio-buttons--tile.njk#L1)
- [Dropdown](https://github.com/uswds/uswds/blob/dw-remove-preview-heds/src/components/dropdown/dropdown.njk#L1)
- [Password reset form](https://github.com/uswds/uswds/blob/dw-remove-preview-heds/src/components/templates/password-reset-form.njk#L1)
- [Sign in form](https://github.com/uswds/uswds/blob/dw-remove-preview-heds/src/components/templates/sign-in-form.njk#L1)
- [Validation](https://github.com/uswds/uswds/blob/dw-remove-preview-heds/src/components/validation/validation.njk#L1)

2021-03-01 21:44 UTC, thisisdano commented
I'll apply the form template to each component that is not, itself, a standalone form:
- Checkbox tile
- Radio tile
- Dropdown
- Validation

2021-03-01 21:56 UTC, thisisdano commented
- Fixed margins in character count
- No longer using `card--compare`, I removed it from the variants

2021-03-02 15:21 UTC, mejiaj approved these changes

2021-03-02 15:22 UTC, merged