Update success dark to vivid variant
uswds/uswds pull request #4183
Opened 2021-05-01 00:55 UTC by maya

Needed for light text on a success background, the current one is drab and doesn't look like a state color and this is more similar to the `success` token.

2021-05-14 19:07 UTC, mejiaj requested changes
Value also needs to be updated on `src/stylesheets/theme/_uswds-theme-color.scss`.

2021-05-14 21:30 UTC, maya commented
@mejiaj both changes done in 6186fcc.

2021-05-15 13:43 UTC, mejiaj approved these changes

2021-05-24 16:53 UTC, thisisdano approved these changes

2021-05-24 16:54 UTC, merged