USWDS - Buttons: Added button type to non-form buttons
uswds/uswds pull request #4187
Opened 2021-05-03 21:20 UTC by mahoneycm

## Description
 
Fixes #3563. Adds `type="button` to all non-form button elements 
 
## Additional information

Example (Accordion):

**BEFORE**

```
 <button class="usa-accordion__button" 
   aria-expanded="{{ item.expanded | default('false') }}" 
   aria-controls="{{ accordion.id_prefix }}{{ item.id }}"> 

```

**AFTER**

```
<button class="usa-accordion__button"
          type="button"
          aria-expanded="{{ item.expanded | default('false') }}"
          aria-controls="{{ accordion.id_prefix }}{{ item.id }}">
```

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ x ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ x ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2021-05-14 13:43 UTC, mejiaj requested changes
Thanks for helping out with this, noticed 2 templates with missing `type`. One is marked in review and the other is in  `src/components/test/sidenav-button.njk:38`.

2021-05-14 13:43 UTC, mejiaj commented on src/components/card/card--standard.njk
>    </li>
Missing type on line 47, 66, and 85.

2021-05-17 19:20 UTC, mejiaj approved these changes

2021-05-17 19:39 UTC, mejiaj commented
Based on guidance in original issue we could remove the `e.preventDefault()` line.
https://github.com/uswds/uswds/blob/f7acaf7e09840f4f84b1398c4d30a977cd7fc1e5/src/js/components/accordion.js#L70-L72

We also need to decide if we're going to add `type` to buttons and button group NJK templates.

2022-05-20 19:26 UTC, amyleadem commented
Closing in favor of PR https://github.com/uswds/uswds/pull/4695, which uses current 3.0 component structure.

2022-05-20 19:26 UTC, closed without merging