USWDS - Accessibility: Added button functionality to usa-button links
uswds/uswds pull request #4385
Opened 2021-11-04 19:22 UTC by mahoneycm

## Description

Resolves #3741 and #3690

Allows for links with `class=usa-button` to look and behave as buttons including being triggered by the space and enter keys

## Additional information

Added `href="#"` to allow links to be targeted through tabbing. 
Renamed `role-button.js` to `button.js`

2021-11-17 17:36 UTC, mejiaj requested changes
Thanks for updating this. Can you resolve conflicts and fix some formatting issues on `href`?

2021-11-17 17:36 UTC, mejiaj commented on src/components/11-button-groups/button-groups.njk
> +    <a href="#" role="button" class="usa-button usa-button--outline">Back</a>
Please remove `role="button"`.

2021-11-17 17:36 UTC, mejiaj commented on src/components/card/_card--basic.njk
> +    <a href='#' class="usa-button">Visit Florida Keys</a>
Double quotes on all `href` attributes.

2021-12-03 17:04 UTC, mejiaj requested changes
@mahoneycm thanks for all your work on this. 

Aside from the requested changes, would you mind creating a unit test for it under `spec/unit`?

2021-12-03 17:04 UTC, mejiaj commented on src/js/components/button.js
> +const toggleUSABtn = function toggleUSABtn(event) {
```suggestion
const toggleButton = (event) => {
```

2021-12-03 17:04 UTC, mejiaj commented on src/js/components/button.js
> +        " ": toggleUSABtn
```suggestion
        " ": toggleButton
```

2022-01-21 19:29 UTC, mahoneycm commented
@thisisdano This was something I worked on a while back for accessibility. Remembered it was wondering if we should readdress?

2023-03-01 21:49 UTC, JackRyan1989 commented
Hi there! There's some interest from Login.gov in having this change implemented. Are there blockers or other considerations preventing this from being merged? Thanks

2023-03-14 15:56 UTC, mahoneycm commented
@mejiaj Updated this PR for the latest USWDS! I also revised the PR description to make the work and problem more understandable. 

This included Dan's request to change `usa-card` buttons to links but that causes the markup to change. If we want to separate that task, we can remove it from this PR

2023-03-31 13:55 UTC, mejiaj approved these changes
LGTM, usually we require a unit test for every new script. I'm not sure on this one given the very limited scope.

2023-04-19 21:17 UTC, amyleadem requested changes
Looks good!
Confirmed that:
- links styled with `.usa-button` are activated by both `space` and `enter`
- links are identified as links in VoiceOver

For good measure, I also searched for any `<a>` tags with `type="button"` and couldn't find any. 

A couple small things:
- Could you update the PR summary to match the changelog/release notes format? (Some details outlined [here](https://github.com/uswds/uswds-site/blob/main/_data/changelogs/_CHANGELOG-README.md#writing-a-good-summary))
- Could you add details to the "Breaking changes" section so that users will know exactly what markup change they'll need to do?
- Also, this shouldn't need to block anything, but I'm wondering if we can make a story that explicitly demonstrates links styled as buttons. We have the example in the `button-group` story, but it is a bit hidden.

2023-04-20 19:55 UTC, mahoneycm commented
@amyleadem Updated the PR description with those two changes!

I agree, I would like to highlight links styled as buttons somewhere as well. Do you think that this should be part of this PR or should I open up a new ticket for that work?

2023-04-21 20:40 UTC, amyleadem approved these changes
Thanks for updating the descriptions. I think it is fine to address the story as a follow-up. Will you open an issue so we don't lose track?

2023-05-03 20:47 UTC, mahoneycm commented
Added changelog PR https://github.com/uswds/uswds-site/pull/2085

2023-05-10 21:16 UTC, thisisdano approved these changes

2023-05-10 21:17 UTC, merged