File upload - make file name accessible to screen readers
uswds/uswds pull request #4406
Opened 2021-11-24 22:28 UTC by amyleadem

Changing aria state after file selection so that the file name will be accessible to screen readers

2021-11-30 22:10 UTC, mejiaj requested changes
Looks pretty good! Thanks for taking this on. Added some quick initial feedback.

2021-11-30 22:10 UTC, mejiaj commented on src/js/components/file-input.js
> +    fileStore.push(' ' + fileName);
```suggestion
    fileStore.push(fileName);
```

2021-11-30 22:10 UTC, mejiaj commented on src/js/components/file-input.js
> +      fileInputEl.setAttribute("aria-label", "You have selected the file: " + fileName);
```suggestion
      fileInputEl.setAttribute("aria-label", `You have selected the file:  ${fileName}`);
```

2021-11-30 22:10 UTC, mejiaj commented on src/js/components/file-input.js
> +      fileInputEl.setAttribute("aria-label", "You have selected " + fileNames.length + " files:" + fileStore);
```suggestion
            fileInputEl.setAttribute("aria-label", `You have selected ${fileNames.length} files: ${fileStore.join(", ")}`);
```

2021-12-01 16:22 UTC, amyleadem commented on src/js/components/file-input.js
> +  fileInputEl.setAttribute("aria-live", "polite");
Thank you. That is a better spot. Moved these lines into buildFileInput().

2021-12-01 16:24 UTC, amyleadem commented on src/js/components/file-input.js
> +    //Push updated file names into the store array
Resolved. Also set up linting so that I can resolve this issues before review.

2021-12-01 17:24 UTC, amyleadem commented on src/js/components/file-input.js
> +  fileInputEl.setAttribute("aria-label", "No file selected");
buildFileInput() is the better spot. Thanks! For your second question, I took your meaning to be that the wording of the label should be pluralized if multiple files are accepted. If you meant anything else, please let me know.

2021-12-01 17:24 UTC, amyleadem commented on src/js/components/file-input.js
> +
All cleaned up

2021-12-01 17:25 UTC, amyleadem commented on src/js/components/file-input.js
> +      fileInputEl.setAttribute("aria-label", "You have selected " + fileNames.length + " files:" + fileStore);
All cleaned up

2021-12-01 17:26 UTC, amyleadem commented on src/js/components/file-input.js
> +      fileInputEl.setAttribute("aria-label", "You have selected the file: " + fileName);
Thanks. All cleaned up.

2021-12-01 17:26 UTC, amyleadem commented on src/js/components/file-input.js
> +    fileStore.push(' ' + fileName);
Fixed

2021-12-03 14:58 UTC, mejiaj commented
Closing in favor of #4415.

2021-12-03 14:59 UTC, closed without merging