Post Getting Started Updates_Nov 30, 2021
uswds/uswds pull request #4412
Opened 2021-11-30 15:48 UTC by mikki-stacey

## Description

Include a high-level description of the issue your pull request fixes; include only one issue per pull request. Please also link to the GitHub issue it resolves.

## Additional information

Include any of the following (as necessary): 

* Relevant research and support documents
* Type of content review needed: stylistic or copy editing
* Screenshot images
* Notes

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2021-12-08 14:49 UTC, mejiaj commented on README.md
> +- Axe dev tools (https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US).
You can make these links by using markdown in the following format `[text](url)`.

```suggestion
- [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html).
- [Axe core](https://www.deque.com/axe/).
- [Axe dev tools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US).
```

2021-12-08 16:23 UTC, mejiaj reviewed
Looks good! But we need to find a solution for SASS Requirements section.

You can view what the page would like like on the doc's site [here →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-test-updated-readme/documentation/developers/).

I've also updated the links to point to new sections in the [Maturity Model page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-test-updated-readme/maturity-model/#level-3-use-uswds-code).

2021-12-09 18:32 UTC, thisisdano approved these changes

2021-12-09 18:45 UTC, thisisdano commented on README.md
> -We recommend using a **minifier** like [csso](https://github.com/css/csso) to compress your final compiled CSS and **sourcemaps** like [`gulp-sourcemaps`](https://www.npmjs.com/package/gulp-sourcemap
Let's reinstate it for now. But I think we should add a "Requirements" section to the **How to Use USWDS** section of the site and add this there.

2021-12-09 18:46 UTC, thisisdano requested changes
Let's make the change James suggested and then we can merge.

2021-12-20 19:06 UTC, mikki-stacey commented
James suggestion was incorporated as part of this PR in the site repo: https://github.com/uswds/uswds-site/pull/1370/files

2022-01-31 19:50 UTC, mejiaj approved these changes
Looks good, thank you @mikki-stacey!

2022-03-09 17:38 UTC, mejiaj approved these changes

2022-03-09 18:16 UTC, thisisdano approved these changes

2022-03-09 18:16 UTC, merged