USWDS - Header: Enable chevrons and add/remove icons to be visible in WHC/Forced Colors mode. Resolves #4453
uswds/uswds pull request #4485
Opened 2022-01-28 21:43 UTC by mahoneycm

## Description

Resolves #4453.

This PR uses the place-icon mixin to create a CSS mask for the Header navigation icons and enables them to be visible in WHC using  `@media (forced-colors: active) {background-color: ButtonText;}`

## Additional information

Currently:
![image](https://user-images.githubusercontent.com/25211650/151624551-1cbbf2b8-4ee7-4954-8794-df28cf3407c7.png)

After Fix:
![image](https://user-images.githubusercontent.com/25211650/151625158-4ad0b432-f533-4faf-99c0-e62bd5d55380.png)

Bonus Mobile view:
![image](https://user-images.githubusercontent.com/25211650/151625208-67156c44-f06a-4e74-81c0-e12fbf9f5638.png)

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2022-02-07 21:05 UTC, mahoneycm commented
I noticed the close button was disappearing on mobile while in WHC. Using the same solution as the chevron, I was able to replace the inline svg with  `place-icon` and add the forced colors media query to remedy this!

---- 

Before:

![image](https://user-images.githubusercontent.com/25211650/152871531-2256a4f2-3f8d-4c99-a02f-0da8c1aad0d2.png)


After:

![image](https://user-images.githubusercontent.com/25211650/152871485-f41ff3d9-538b-4d58-9d8d-1a7e7b9c5e9e.png)

2022-03-21 15:33 UTC, thisisdano approved these changes
Nice work!

2022-03-21 18:00 UTC, mejiaj requested changes
Looks and works pretty well. Thank you!

Some additional improvements we could make:
- Add some HCM styles to the navigation bar [[_add-bar.scss]](https://github.com/uswds/uswds/blob/11e947cc1aa4875c4c406ff203bfbc1ac8b11bb1/src/stylesheets/core/mixins/_add-bar.scss#L18) (used in `usa-current` here and in sidenav)
- Add a background or border to the search button for HCM only

2022-03-21 23:12 UTC, amyleadem commented on src/stylesheets/components/_navigation.scss
> +$vertical-align: "auto";
I don't believe`vertical-margin: auto` has any meaning. Do you mean `middle`?

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

2022-03-21 23:25 UTC, amyleadem commented
@mahoneycm 
Visual note: In standard mode, there is a difference in color for the expand icons. `develop` currently shows the icons as black, in this PR the col.ors are gray and blue.
![image](https://user-images.githubusercontent.com/93996430/159378782-9f6e50d4-0303-4db9-bc27-ca34140d8bec.png)

2022-03-25 18:31 UTC, mahoneycm commented
Closed in favor of #4604

2022-03-25 18:31 UTC, closed without merging