USWDS Beta 3.0 - Component migration phase 3
uswds/uswds pull request #4506
Opened 2022-02-08 19:00 UTC by amyleadem

This PR creates storybook listings for the following components from @mejiaj list in https://github.com/uswds/uswds/issues/4496

- [x]  Validation
- [ ]  Name form
- [ ]  Address form
- [ ]  Password reset form
- [ ]  Side navigation default
- [ ]  Side navigation one level
- [ ]  Side navigation two levels
- [ ]  Side navigation three levels
- [ ]  Side navigation compare
- [ ]  Identifier default
- [ ]  Identifier multiple logos
- [ ]  Identifier no logos
- [ ]  Identifier tax disclaimer
- [ ]  Identifier default Spanish
- [ ]  Identifier multiple logos Spanish
- [ ]  Identifier no logos Spanish
- [ ]  Identifier tax disclaimer Spanish
- [ ]  Footer default
- [ ]  Footer big
- [ ]  Footer slim
- [ ]  Sign in form

2022-02-09 22:03 UTC, amyleadem commented
Some notes:
-I left out the items for Side nav compare and side nav default - I figured it was covered by the Level 1-3 stories and their docs. If you'd like to see a compare story, let me know.
- I discovered a few style variances from the component presentation on uswds-site:
    - Forms: text-decoration exists under required asterisk by default, is hidden in uswds-site
    - Identifier component: missing the external link icon that is added to uswds-site
    - Footer component: the width of content is different in each build, I believe it is due to theme setting for $theme-grid-container-max-width (uswds has it set to 'desktop', uswds-site to 'widescreen')
        - Is this a style bug? Should all footer elements align to the same width?
        - Width presentation difference:
        ![image](https://user-images.githubusercontent.com/93996430/153281191-1f91cfd3-5222-4e1a-9759-9631f02433c2.png)

2022-02-10 15:40 UTC, amyleadem commented
I noticed that on the mailing address form, the assistive/accessibility markup from combo-box.js is printed in the storybook html tab, but does not show under component code in the [docs site](https://designsystem.digital.gov/templates/form-templates/address-form/). 
Will this be a problem?

2022-02-14 22:13 UTC, mejiaj commented
> Some notes:
> 
> * I left out the items for Side nav compare and side nav default - I figured it was covered by the Level 1-3 stories and their docs. If you'd like to see a side nav compare story, let me know.

This is okay for now. We use compare in the [documentation](https://designsystem.digital.gov/components/side-navigation/). We can test this or the `library--develop` branch to see if it's needed or not. 

_If you're curious_ you can install this branch on USWDS-Site based on the instructions [here](https://github.com/uswds/uswds-site#updating-the-uswds-version). You could branch off and update this [PR](https://github.com/uswds/uswds-site/pull/1216).

2022-02-14 22:28 UTC, mejiaj requested changes
Great work! 

Just 2 minor comments on placement of an `endif` and the Storybook label for the default footer (call it the default instead of medium in the Story).

There's also some additional investigation needed for that normalize issue.

2022-02-14 22:28 UTC, mejiaj commented on src/templates/usa-sign-in/includes/_value-props.twig
> -      'description': '<strong>Value proposition 3:</strong> Vivamus nec velit sed leo scelerisque laoreet vestibulum.>'
Good catch, thanks for fixing these!

2022-02-15 17:45 UTC, amyleadem commented
@mejiaj I have resolved the comments above, including resolving the normalize conflict by moving the global abbr[] style out of placeholders/forms and into usa-form.scss. Please let me know if you'd rather have that rule globally-scoped instead.

2022-02-16 14:23 UTC, mejiaj approved these changes

2022-02-16 14:23 UTC, merged