USWDS - Select: Include standard "multiple" stylings. Resolves #4423
uswds/uswds pull request #4766
Opened 2022-06-03 17:22 UTC by mahoneycm

## Preview

Select →

## Description

Resolves #4423 

> According to the [HTML 5 standard](https://html.spec.whatwg.org/multipage/rendering.html#the-select-element-2), a select element whose multiple attribute is present is "expected to render as an inline-block box whose height is the height necessary to contain as many rows for items as given by the element's display size, or four rows if the [size] attribute is absent." This standard behavior has the benefit of making it obvious that multiple selections can be made and users have come to expect and depend on this visual clue. All of the major browsers implement this behavior by default. The USWDS component system suppresses this behavior, ignoring the size attribute as well as the standard's instructions for the height of the box in the absence of that attribute.

This PR

- Adds expected styling for `select` when the multiple attribute is present
- Sets default styling as described by `HTML 5 standard`
- Adds storybook controls to enable the `multiple` attribute and set `size` attribute
- If `size = 0` it will act as if the `size` attribute is absent and do the standard default of four rows.

## Additional information

Standard select: 

<img width="257" alt="image" src="https://user-images.githubusercontent.com/25211650/171913776-53208b7e-7da4-42da-80e4-68f28ffde933.png">

Multiple Enabled:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/25211650/171913847-e45c1248-4bd7-44c4-9a76-a14e56bba7c2.png">

New Storybook controls:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/25211650/171913932-b0f0ff75-c15d-4fd0-9b71-2e266173940f.png">

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2022-06-06 15:35 UTC, amyleadem requested changes
Looks like this is working well! 
A couple of thoughts:
- We should have a separate story in Storybook for when `multiple` is true
- The padding on the select box can cause text to get cut off if the `size` is less than the item count. It might be better to add the padding to the options when `multiple` is true.
![image](https://user-images.githubusercontent.com/93996430/172193474-1a66b2b2-c1a6-4ddc-9f4c-0806e24f9662.png)


- Additionally, we have this note in our [docs](https://designsystem.digital.gov/components/select/) for select:
    "When to consider something else: Multi-select. If you need to allow users to choose more than one option at once. Users often don’t understand how to choose multiple items from select elements. Use checkboxes instead." 
    - Are we now allowing multiple select as a recommended practice? If this is now an acceptable pattern, we should remove this line, provide use-case recommendations, and should add some notes about both `multiple` and `size` in our documentation. 
    
Let me know if you have questions!

2022-06-06 16:57 UTC, mahoneycm commented
Thanks @amyleadem!

- Having a second story could be a good idea! I feel like it also depends on if we want this advertised as an option or not, because of the checklist note you mentioned
- I'm open to suggestions on how to handle the padding. I initially left it because when it is missing, it becomse a little less clear that you can scroll to see more options (i.e. if size is not set and it is default to 4 rows, but there are more than four options):  
<img width="268" alt="image" src="https://user-images.githubusercontent.com/25211650/172206769-b6c72798-efcc-40fc-b9e8-2d33092262f3.png">

_(of course the scroll bar is a good indicator)_

- I also asked Dan about the guidance re: checkboxes but the issue is that the multiple select is a native functionality that the HTML 5 standards require. Dan said the following: "So yes, I think that in most instances, checkboxes are preferable to multi-select.  Multi-select is bad UI, I’d say, like 99.99% of the time. That said, native multi-select should work with USWDS and should probably work as the user suggests."

2022-06-10 19:47 UTC, mejiaj commented
>The padding on the select box can cause text to get cut off if the size is less than the item count. It might be better to add the padding to the options when multiple is true.

I think the padding is coming from the default input styles. It seems expected to leave it in by default for this. 

I agree with Dan's comments. We're not recommending this as a new pattern, we're just making sure USWDS styles don't break the expected behavior. We also don't have research to suggest otherwise, so we can leave guidance as-is. Good consideration though!

I agree with @amyleadem, a separate story would be better.

2022-06-13 19:35 UTC, mejiaj requested changes
Thanks Charlie, I've added some feedback.

2022-06-13 19:35 UTC, mejiaj commented on packages/usa-select/src/usa-select--multiple.twig
> +
Can we move this to a directory `usa-select/test/test-patterns`?

Similar to what we did with this component test template
https://github.com/uswds/uswds/blob/1db0e68d7e5cf21ae52f2d8a29d5963c7aa1b681/packages/usa-combo-box/src/test/test-patterns/test-usa-combo-box.twig

2022-06-13 19:35 UTC, mejiaj commented on packages/usa-select/src/usa-select.json
> +}
Let's move this too or just add it to the new test template inline.

2022-06-14 13:33 UTC, mejiaj requested changes
Tiny changes, otherwise LGTM!

2022-06-14 13:33 UTC, mejiaj commented on packages/usa-select/src/test/test-patterns/usa-select--multiple.twig
> +
Can you double-check the empty lines at end of file? Locally shows 2 empty lines, should be 1.

2022-06-14 13:33 UTC, mejiaj commented on packages/usa-select/src/usa-select.stories.js
> +import TestMultiple from "./test/test-patterns/usa-select--multiple.twig";
Let's just rename this to Test for now.

2022-06-14 13:33 UTC, mejiaj commented on packages/usa-select/src/usa-select.twig
> +
This one also shows an extra line at end.

![image](https://user-images.githubusercontent.com/3385219/173589668-6f0c6626-b1d6-457d-9622-964d23f935ad.png)

2022-06-17 19:47 UTC, mejiaj approved these changes

2022-06-23 18:54 UTC, amyleadem approved these changes
Looks good to me!

2022-07-05 16:35 UTC, merged