USWDS - update v2 readme for npm
uswds/uswds pull request #4846
Opened 2022-07-06 16:16 UTC by amyleadem

## Description

Update the README for the `uswds` npm package to point users to the new `@uswds/uswds` package.  

Closes https://github.com/uswds/uswds/issues/4843

Preview link: [README in Github](https://github.com/uswds/uswds/pull/4846/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

### Problem
Users should be able to quickly and easily find the most recent version of USWDS to install. Currently, when you search for "USWDS npm" in Google or "uswds" on the [npmjs.com](https://www.npmjs.com/search?q=uswds) website, you are directed first to the `uswds` package instead of the current `@uswds/uswds` package. Once on the [`uswds` package page](https://www.npmjs.com/package/uswds), there is nothing to indicate that USWDS 3.0 or [@uswds/uswds](https://www.npmjs.com/package/@uswds/uswds) exists, so users can be left thinking that 2.13.3 is the most recent version. 

### Solution
Update the README for v2 to alert users that USWDS 3.0 exists, and that they can install it under the new scoped package at @uswds/uswds.

_Please note, this will update only the v2 readme that is pulled into the the `uswds` npm package page. This will not affect the v3 readme or the `@uswds/uswds` page_.

## Additional information

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2022-07-06 18:14 UTC, bonnieAcameron approved these changes
Checked for:

- [x] Typos
- [x] Formatting
- [x] Information gaps
- [x] Conflicting information

2022-07-18 04:06 UTC, thisisdano requested changes

2022-07-18 04:06 UTC, thisisdano commented on README.md
> +Starting with version 3.0, the latest updates to USWDS are now published to the [@uswds/uswds](https://www.npmjs.com/package/@uswds/uswds) package.
Rewritten with active voice and a little more detail

```suggestion
Starting with USWDS 3.0, we're publishing USWDS as a scoped package at [@uswds/uswds].(https://www.npmjs.com/package/@uswds/uswds).
```

2022-07-18 04:06 UTC, thisisdano commented on README.md
> +This unscoped `uswds` package will remain active for legacy use.
```suggestion
This unscoped `uswds` package will remain active for any updates to USWDS 2.x.
```

2022-07-18 15:24 UTC, amyleadem commented
@thisisdano Thanks for the review. I have committed your requested changes.

Now that I am revisiting, I do wonder if we should help users find the uswds npm page from the @uswds/uswds page as well. Maybe something more subtle in the [long-term support of 2.x section](https://www.npmjs.com/package/@uswds/uswds#user-content-long-term-support-of-v2x)? Let me know if you are interested in something like that and I can open up an issue for it.

2022-08-01 16:32 UTC, thisisdano commented
Yes, let's do that. I'm going to merge this and we can make a new issue around adding the old package location to the long-term support section

2022-08-01 16:32 UTC, merged