Mm inclusive patterns in page navigation
uswds/uswds pull request #4860
Opened 2022-07-12 12:37 UTC by mitchmoccia

The goal is to provide a generic enough, In-page navigation that works on any page, while providing a basis for guidance for developers who want to customize it further.

Federalist link:
https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/mm-inclusive-patterns-in-page-navigation/components/accordion/

## Features
### Design updates
- reduced size of font
- reduced size of vertical bar
- Tightened up the vertical and horizontal padding for each link
- visibility set to hidden on screens smaller than tablet
- changed vertical active bar color to secondary-dark (in-palette red)

### Code
-  JS and styles are now coming from the USWDS component site (from my working branch mm-inclusive-patterns-in-page-navigation)
  - JS not needed inside sidenav.js in the uswds-site
- in-page nav links are created dynamically after the page loads
- dynamically creates and adds the hash value to each link in sequential order
- dynamically creates matching anchor tags that get injected after each target heading 
  - this eliminates the need for manual ID matching in a page, it's done automatically
- does not require adding new grid layout HTML
  - when wrapped in a parent div with in-page-navigation class, flex does the work of positioning the in-page nav
- offset anchor provides a gap when a target heading is clicked to

### Requirements to implement
- wrapper with class in-page-nav-container for main-content and a new div with and id of in-page-navigation
- element with class site-subheading and text such as On this page or Table of contents

## TO DO 
- work out the In-page navigation page on uswds-site to display of Component preview for in-page navigation along with the dynamic in-page nav actually working (this is the only page with
- give focus to content section when enter key is clicked
- iron out the speedy scrolling issue that causes the nav to jump when accordion is closed/opened
- larger break point for nav to disappear (768px may be the sweet spot)

2022-07-14 16:11 UTC, mejiaj requested changes
A lot of great work here, nice job! Added some suggestions and questions. Overall some things to lookout for:

- Let's sync this with `develop`
- Make sure you run `prettier` for both SASS/JS
- Look at ESLint errors in JS
- Let's follow best practices for creating HTML elements in JS with `createElement()`
- Let's be careful with using `:not()` selector by itself

2022-07-18 03:08 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/styles/_usa-in-page-navigation.scss
> +    &:not(.usa-button) {
I added the where selector, did notice this is not in use in any component with many instances of :not.

2022-07-18 03:08 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/styles/_usa-in-page-navigation.scss
> +.usa-in-page-navigation.usa-sidenav {
Reworked this to only utilize the single component class.

2022-07-18 03:09 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/styles/_usa-in-page-navigation.scss
> +      padding: 0.3rem 0.8rem;
Ok changed this to units .5 and 1

2022-07-18 03:09 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +      }
This is done.

2022-07-18 03:10 UTC, mitchmoccia commented on packages/usa-icon/src/img/sprite.svg
> +<?xml version="1.0" encoding="utf-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><symbol viewBox="0 0 24 24" id="accessibility_new" xmlns="http://www.w3.org/20
Merged in the latest from develop.

2022-07-18 03:11 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/styles/_usa-in-page-navigation.scss
> +    }
This all came from side nav originally, so the 3 levels still exist there, but I refactored it here.

2022-07-18 03:11 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/styles/_usa-in-page-navigation.scss
> +  #in-page-navigation {
Using the class now.

2022-07-18 03:12 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/styles/_usa-in-page-navigation.scss
> +  .offset-anchor {
Offset anchor gets injected by the JS after the DOM loads. Every target H2 and H3 gets this added right after the heading element. It's part of the dynamic creation process so the IDs of the links in the in-page nav don't have to match the IDs in every heading, they are just sequentially created (like section_0, section_1) and added.

2022-07-18 03:12 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +}
I ESLinted this and found there is the following error so I held off using this for now:

```js
'domready' should be listed in the project's dependencies. Run 'npm i -S domready' to add it eslint[import/no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/no-extraneous-dependencies.md)
```
when-dom-ready.js and start.js have the error.

2022-07-18 03:13 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +      if (headings && headings.length) {
Done, added this check on line 124 as well... Also had to add this.container in the check to avoid errors on pages without the in-page nav div.

2022-07-18 03:14 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +          let tag = heading.tagName.toLowerCase();
Changed everything to align with ESLint recommendations.

2022-07-18 03:15 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +        const inPageNav = `<ul class="usa-in-page-navigation usa-sidenav">${inPageNavigationInner}</ul>`;
The ul gets dynamically added to the dom... What's in the template is a div with the in-page-navigation class (e.g. not usa-in-page-navigation). Can work to improve/clarify this more.

2022-07-18 03:16 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +        if (location.hash) {
Yes, updated and added window.

2022-07-18 03:16 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +        top: section.offsetTop + 140,
This is used to dial in where the page is scrolled to when a link is clicked, giving space from the top to compensate for the fixed header and main nav. I changed this to be a setting (this.headerOffset) in the InPageNavigation object.

2022-07-18 03:17 UTC, mitchmoccia commented on packages/usa-in-page-navigation/_index.scss
> +@forward "uswds-fonts";
I initially copied the sidenav package to get in-page navigation rolling. I have removed the sidenav selector from the component.

2022-07-18 04:14 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +          const originalHeadingContent = heading.innerHTML;
I found where you did an XSS audit (e.g. 8 mos ago, usa-combo-box) and utilized innerHTML with the Sanitizer API to circumvent potential security vulnerabilities, e.g.:
```js
listEl.innerHTML = "";
    optionHtml.forEach((item) =>
      listEl.insertAdjacentElement("beforeend", item)
    );
```

I implemented this here. Curious to know your thoughts? @mejiaj

2022-07-18 04:15 UTC, mitchmoccia commented on packages/usa-in-page-navigation/src/index.js
> +      //section.focus();
Uncommented this.

2022-07-22 13:31 UTC, khadem56 approved these changes

2022-11-02 05:18 UTC, thisisdano commented
Closing in favor of https://github.com/uswds/uswds/pull/4918

2022-11-02 05:18 UTC, closed without merging