USWDS - Align alert content with banner
uswds/uswds pull request #4922
Opened 2022-08-18 21:27 UTC by amyleadem

## Description

Include a high-level description of the issue your pull request fixes; include only one issue per pull request. Please also link to the GitHub issue it resolves.

## Additional information

Include any of the following (as necessary): 

* Relevant research and support documents
* Type of content review needed: stylistic or copy editing
* Screenshot images
* Notes

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

2022-08-23 16:47 UTC, amyleadem commented on packages/usa-site-alert/src/styles/_usa-site-alert.scss
> -
Removed because it was only referenced once in our system. Let me know if we need to preserve this mixin for project use, etc

2022-08-29 16:01 UTC, mejiaj requested changes
Both alert and site alert look good! Added some suggestions for code clarity.

2022-08-29 17:43 UTC, amyleadem commented on packages/usa-alert/src/styles/_usa-alert.scss
> +  &.usa-alert--no-icon {
The default `usa-alert` and `usa-site-alert` classes do not have an icon by default, but the default styles for status variants (usa-alert--emergency, usa-alert--info, etc) do have default icons. So the `usa-alert--no-icon` class is useful if, for example, a user wants emergency styling without the icon.

2022-08-29 17:43 UTC, amyleadem commented on packages/usa-alert/src/test/test-patterns/test-alert-comparison.json
> +  }
Good catch. Fixed in [29ca555](https://github.com/uswds/uswds/pull/4922/commits/29ca5557ead742902788bf36787c70b9e77492a3)

2022-08-29 17:44 UTC, amyleadem commented on packages/uswds-core/src/styles/mixins/helpers/alert-status-styles.scss
>    $banner-text-color-token: get-color-token-from-bg(
Good find. Thanks! Removed in [61ab99c](https://github.com/uswds/uswds/pull/4922/commits/61ab99ca1640d47c510b32825f807e92447f6307)

2022-08-29 17:46 UTC, amyleadem commented on packages/usa-site-alert/src/styles/_usa-site-alert.scss
>  }
They can, we just need to add in `.usa-alert` for specificity, but this makes it more consistent with other site-alert sass. Appreciate the suggestion. Updated in https://github.com/uswds/uswds/pull/4922/commits/dae7ad6d40fe250313f4b67956203dcd53c4d1a0

2022-08-29 17:46 UTC, amyleadem commented on packages/uswds-core/src/styles/mixins/helpers/alert-status-styles.scss
> +@mixin alert-status-styles-background($name) {
Updated to alert-status-wrapper-styles in [51da0ce](https://github.com/uswds/uswds/pull/4922/commits/51da0cec5f59a414e7eb3987bd2a495a9ccd609a)

2022-08-29 17:47 UTC, amyleadem commented on packages/uswds-core/src/styles/mixins/helpers/alert-status-styles.scss
> +@mixin alert-status-styles($name, $icon) {
Updated to `alert-status-body-styles` in https://github.com/uswds/uswds/pull/4922/commits/51da0cec5f59a414e7eb3987bd2a495a9ccd609a

2022-08-29 17:50 UTC, amyleadem commented
Thanks for the review @mejiaj. Let me know if you see anything else.

2022-09-01 13:58 UTC, mejiaj approved these changes
Great, thanks @amyleadem.

Tested the following
- [x] Cross browser visual check (all screen sizes)
- [x] Code style
- [x] Ran `npm test`

No issues found.

2022-09-26 15:43 UTC, thisisdano approved these changes
Nice improvement!

2022-09-26 15:43 UTC, merged