Avoid unit math on settings until after configured unit resolved
uswds/uswds pull request #5076
Opened 2022-12-21 15:55 UTC by aduth

## Summary

Attempts to fix #5075 by avoiding math on configurable settings values which could result in an invalid unit token. The effect should be the same, but ensures that the configurable unit value is resolved before attempting any math on it.

## Related issue

Fixes #5075

## Problem statement

Developers should be able to configure settings to any valid unit and the build should pass.

## Solution

Resolves configured unit value before performing math on it.

2023-01-11 15:15 UTC, mejiaj approved these changes
Thank you! I was able to confirm the bug and the fix.

I also looked for other instances where we might be doing math inside of units, but didn't find any.

2023-01-18 18:35 UTC, amyleadem requested changes
@aduth Thanks for fixing this! 
I was able to confirm the issue and that the updates here fix the problem. I also confirmed that there were no visual discrepancies in the affected areas for banner and alert. 

I did notice one more instance of calculations happening inside `units()` in `usa-banner`: https://github.com/uswds/uswds/blob/develop/packages/usa-banner/src/styles/_usa-banner.scss#L187 

Would you be able to update that as well?
Let me know if you have questions. Thanks again!

2023-01-19 17:51 UTC, aduth commented
Hi @amyleadem , in that case is the variable `$size-touch-target` meant to be configurable by a theme? I was under the impression it's a hard-coded value which wouldn't be prone to the same sorts of conflicts.

https://github.com/uswds/uswds/blob/e75f3f347170ebfe472bba9719935a4f5ba38b69/packages/uswds-core/src/styles/variables/size-touch-target.scss#L1

That being said, even if it's not configurable, I could see it being helpful to update it anyways for consistency.

2023-01-19 17:52 UTC, aduth commented
Updated the banner unit math in 3d830f7 .

2023-01-19 22:30 UTC, amyleadem approved these changes
Thanks for the quick response on this @aduth! Looks good to me.

2023-02-28 19:15 UTC, thisisdano approved these changes
Thank you!

2023-02-28 19:15 UTC, merged