USWDS - Links: Fix invisible text when styled as buttons within forms. Resolves #5066
uswds/uswds pull request #5112
Opened 2023-01-27 17:04 UTC by mahoneycm

## Problem statement

Links styled as buttons inherit `typeset-link` when nested within forms. This causes the link text color to match the button background color and becomes unreadable. 

## Solution
By adding `:not(.usa-button)` we can avoid links with the `usa-button` class and preserve the button styles.

## Related issue
Closes #5056 

## Testing and review
1. Visit a form pattern that has a button such as sign in, or reset password.
2. Open the inspector tool and inspect the button
3. Right click the html and select "Edit as HTML"
4. Replace button tag with the following: `<a class="usa-button" href="#">Button Text</a>`
5. Confirm button text is still legible

## Screenshots

### Before:
![image](https://user-images.githubusercontent.com/25211650/215148002-b219d038-9abc-42b5-b8dc-630ed1890a10.png)

### After
![image](https://user-images.githubusercontent.com/25211650/215148092-cf4feb88-9146-4ca0-9c79-335d1be4aa11.png)

Before opening this PR, make sure you’ve done whichever of these applies to you:
- [x] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `develop`).
- [x] Run `npm run prettier:scss` to format any Sass updates.
- [x] Run `npm test` and confirm that all tests pass.

2023-01-27 18:19 UTC, mahoneycm commented
@mejiaj Added `:where` selector to reduce specificity

2023-02-01 18:47 UTC, amyleadem requested changes
This seems like a good, low-impact solution. I confirmed that both standard links and links with `.usa-button` look as expected inside `.usa-form`.  I checked in Firefox, Safari, Chrome, and Edge. 

One thing - can you update the PR description with a summary that can be used in the release notes and changelog?

It also might be good to tag the related issue for 3.4.0.

2023-02-02 14:30 UTC, mahoneycm commented
@amyleadem  Added a changelog appropriate description! Let me know if you would word this any different:

> **Fix invisible link text for anchors styled as buttons within forms**. We specified which form links should not receive `typeset-link`. Now link text does not match the primary button color when nested inside of a form and the `usa-button` class is present.

2023-02-02 17:20 UTC, amyleadem approved these changes
@mahoneycm The style fix looks good. 
Not within the scope of this issue, but we should look into creating guidance to advise people against using button-styled links in forms and instead use buttons. It has some accessibility/usability implications.
That said, I still think that our CSS should accommodate the pattern in case there _is_ a valid use case. I understand there might be differing opinions on that though.

2023-02-06 18:07 UTC, mahoneycm commented
@mejiaj  bumping for review when you get the chance!

2023-02-22 17:23 UTC, mejiaj approved these changes
Links with `usa-button` are rendering correctly and regular anchor's aren't affected. Nice work!

**How I tested**
I modified `usa-sign-in-form.twig` with the following markup:

```twig
// usa-sign-in-form.twig
<input class="usa-button" type="submit" value="{{ submit.label |default('Sign in') }}">
<a href="#" class="usa-button">Testing link with button class</a><br>
<a href="#">A link without usa-link</a><br>
<a href="#" class="usa-link">With usa-link</a><br>
```

Got this result:
![image](https://user-images.githubusercontent.com/3385219/220706703-3d1c3799-ac70-4ecf-a38c-f72bed11b0c3.png)

---

Also tested in Safari, Firefox, and Chrome.

2023-03-08 00:22 UTC, merged