USWDS - Card: Fix `$theme-card-border-width` calculation errors
uswds/uswds pull request #5325
Opened 2023-06-07 18:20 UTC by mahoneycm

# Summary

Resolves errors based around setting `$theme-card-border-width` to `0` or string tokens.

## Breaking change

This is not a breaking change.

## Related issue

Closes #5162 

## Related pull requests

Changelog entry →

## Preview link

Card storybook preview →
Test repo →

## Problem statement

### Setting `$theme-card-border-width` to zero

This caused errors when setting the card radius using the `calc()` function because `calc()` cannot take unitless numbers[^1]

![Screenshot 2023-02-23 at 11 20 30 AM](https://user-images.githubusercontent.com/87388914/220974358-7df31e45-7543-4c88-b2d7-82ffe33f8691.png)

### Setting `$theme-card-border-width` to a string token

Extdent variants of card use the variable to set a negative border width the following calculation:

```scss
@include u-margin-x(-$theme-card-border-width);
```

When using a string token like `"05"`, this results in `u-margin-x(-"05")` which breaks the margin function because it is not a valid USWDS token

![image](https://github.com/uswds/uswds/assets/25211650/d14d8a55-a4ec-4f23-96a4-2a3d0a83342d)

## Solution

1. Update `$system-spacing.special` 0 value from `0: 0` to `0: spacing-multiple(0)`
   - This falls in line with other `$system-spacing` tokens 
      - `"05": spacing-multiple(0.5)`
      - `1: spacing-multiple(1),`
   - `_card.scss` is using sass interpolation `#{}` which maintains the `rem` unit passed in by the units function
      - `#{units($theme-card-border-width)} ` results in `0rem`
      - Other references to `units(0)` still result in unitless `0`
   - `units()` is the only function that references `$project-spacing-standard`
   - Resolves this issue anywhere `units(0)` is used within a `calc()` function
2. Update method to get negative margins to work with string token values
   - Changed to a solution found in `_footer.scss`
   - Works with all width tokens mentioned in `_border`
```diff
- @include u-margin-x(-$theme-card-border-width);
+ @include u-margin-x($theme-site-margins-mobile-width * -1); 
```

## Testing and review

1. Confirm bugs exist 
    - On `develop`, set `$theme-card-border-width` to `0`
    - Inspect `.usa-card__img` and verify `calc()` is not working correctly
    - Set `$theme-card-border-width` to `"05"` _(or another string token)_ 
    - Inspect build error
2. Checkout USWDS-Sandbox test repo →
7. `$theme-card-border-width` will be set to `0` by default
8. Inspect `.usa-card__img` and verify `calc()` is working correctly
9. Go to `_uswds-theme.scss` and set `$theme-card-border-width` to `"05"`
10. Verify that there are no build errors
11. Inspect `.usa-card__media--exdent` class and check negative margins are set correctly

[^1]: https://sass-lang.com/documentation/values/calculations#:~:text=Other%20calculations%20don%E2%80%99t%20allow%20unitless%20numbers%20to%20be%20added%20to%2C%20subtracted%20from%2C%20or%20compared%20to%20numbers%20with%20units.

Before opening this PR, make sure you’ve done whichever of these applies to you:
- [x] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `develop`).
- [x] Run `npm run prettier:sass` to format any Sass updates.
- [x] Run `npm test` and confirm that all tests pass.

2023-06-27 23:21 UTC, amyleadem commented
Hi @mahoneycm,
I hit a series of warnings when I set `$theme-card-border-width: 0` (They should be visible in your sandbox demo if you set `$theme-show-compile-warnings` to `true`).
```
Warning: `0rem` is not a USWDS `margin-horizontal` token. This is OK, but only components built with standard tokens can be accepted back into the system. Standard `margin-horizontal` values: 1px, 2px, 05, 1, 105, 2, 205, 3, neg-1px, neg-2px, neg-05, neg-1, neg-105, neg-2, neg-205, neg-3, neg-4, neg-5, neg-6, neg-7, neg-8, neg-9, neg-10, neg-15, 4, 5, 6, 7, 8, 9, 10, 15, card, card-lg, mobile, 05em, 1em, 105em, 2em, 0, auto
```

This happens with many of the accepted token values for the setting. Is it possible to resolve these?

2023-07-05 18:29 UTC, mahoneycm commented
@amyleadem 
CC: @mejiaj 

For context, the rem unit is caused by the `spacing-multiple()` function I added to the `0` value in `$system-spacing.special`. The functions that do not require the unit, drop the unit on output to just become `0` _(example of this below)_

how do we feel about resolving the warning by adding `0rem` to the `$partial-values` map? The warning disappears when this one line is added.

```diff
$partial-values: (
  zero-zero: (
    0: 0,
+   0rem: 0,
  ),
```

or by adding a rem specific map similar to [$system-spacing-em](https://github.com/uswds/uswds/blob/218b91a2048074f534f776bdf1369cf51ae96508/packages/uswds-core/src/styles/tokens/units/spacing-em.scss#L4):

```scss
$system-spacing-em: (
  small: (
    "05em": 0.5em,
    1em: 1em,
    105em: 1.5em,
    2em: 2em,
  ),
);
```

I see a benefit in this because `calc()` functions require the unit to operate, so we need to be able to pass `0rem` to these functions if we want to allow zero values. Functions that do not require the unit will still return a unitless value, such as

```scss
$theme-card-border-width: 0;

.usa-card__media--exdent {
  @include u-margin-right(units($theme-card-border-width) * -1);
  @include u-margin-left(0);
}
```

Returns: 
![image](https://github.com/uswds/uswds/assets/25211650/5b5b33ea-34c5-41cc-8208-c4bca67c7a5d)

2023-07-10 16:28 UTC, mejiaj requested changes
> For context, the rem unit is caused by the `spacing-multiple()` function I added to the `0` value in `$system-spacing.special`. The functions that do not require the unit, drop the unit on output to just become `0` _(example of this below)_

Are you saying this is what's causing the rem warning on compile? The warnings point to examples like this:

```scss
  @include u-margin-left(units($theme-card-border-width) * -1);
```

Which makes sense because `u-margin-left` expects tokens, not the value of `units()`.


> how do we feel about resolving the warning by adding `0rem` to the `$partial-values` map? The warning disappears when this one line is added.

Adding unit specific values, in this case `rem` seems like a can of worms. Because then we'd have to add in values for `em, px, ch, and any other unit` that could potentially fail.

Have we investigated the following?
1. Swapping utility mixins for native properties so we can pass `units()`.
2. Using internal logic to check for border width values of 0 or none _and then_ passing that to `calc()`.
3. Alternatively, we could get rid of `calc()`, but this doesn't seem like a long term solution.

2023-07-20 20:16 UTC, mahoneycm commented
@mejiaj swapping the utility mixins for native properties works. Should I follow that pattern throughout the card scss? Or only where `calc()` is used?

There also seems to be some general cleanup that can be done here. It references `usa-card__header--exdent` which isn't mentioned on the [guidance page](https://designsystem.digital.gov/components/card/#guidance:~:text=between%20card%20elements.-,Card%20variants,-Variant) and doesn't seem to cause any changes to the placement of the header.

Let me know if you want me to go ahead and swap the native properties and I can push up a PR. I'll remove the exdent class definition as well and we can discuss from there

2023-07-20 20:47 UTC, mejiaj commented
I was originally thinking _only_ where `calc()` is used. Do you see any issues with this approach?

2023-07-20 20:48 UTC, mahoneycm commented
@mejiaj Nope! That sounds good to me and removed the errors in my initial testing! I was just curious on where you stood from a code consistency standpoint. I'll work on getting these updated.

2023-07-28 21:58 UTC, amyleadem approved these changes
I appreciate the test you built out, @mahoneycm . Always makes it easy.

Looks good to me!

- [x] Confirm no compilation or `calc` errors with string tokens
- [x] Confirm no compilation or `calc` errors with `0` value
- [x] Confirm no visual regression
- [x] Confirm no compile warnings

2023-08-02 16:34 UTC, mejiaj approved these changes
Looks good. I didn't find any visual regressions in USWDS or Sandbox branches.

I've tested and can confirm:

- [x] Zero visual regressions.
- [x] Zero compile errors. 
- [x] Border width tokens work in `$theme-card-border-width`[^1].

### Sandbox testing

Thanks for including a test sandbox branch. I made additional changes locally. Changes include:
- Install and compare USWDS latest.
- Updating flag default to use media exdent.

[^1]: ⚠️  Documentation for `$theme-card-border-width` shows `units` as token, but border width tokens only support $system-spacing maps for `smaller, small, and zero-zero. See [_properties.scss](https://github.com/uswds/uswds/blob/cm-card-border-width-0/packages/uswds-core/src/styles/_properties.scss#L124-L132), which depends on  [spacing.scss](https://github.com/uswds/uswds/blob/35a9e8af9a8142466178a1cba2dc365495454ffa/packages/uswds-core/src/styles/tokens/units/spacing.scss#L5-L22)

2023-08-02 16:34 UTC, mejiaj commented on packages/uswds-core/src/styles/tokens/units/spacing.scss
> +    0: spacing-multiple(0),
Curious as to why this was changed?

2023-08-03 13:56 UTC, mejiaj commented on packages/uswds-core/src/styles/tokens/units/spacing.scss
> +    0: spacing-multiple(0),
@mahoneycm thanks for the reply and apologies for missing it. I must've confused it since the formatting is similar to the testing & review list 🤦.

2023-08-11 16:34 UTC, merged