USWDS - `3.6.0`: Npm audit fix
uswds/uswds pull request #5461
Opened 2023-08-25 14:59 UTC by mahoneycm

# Summary

Ran `npm audit fix` on `develop` branch after `3.6.0`

## Vulnerabilities

### Before

```js
33 vulnerabilities (4 moderate, 29 high)
```

### After

```js
30 vulnerabilities (1 moderate, 29 high)
```

## Breaking change

This is not a breaking change

## Related pull requests

_Indicate if there are other pull requests necessary to complete this issue._

## Preview link

Preview link →

## Testing and review

1. Checkout branch
2. Run npm install
3. Confirm no build errors 
4. Confirm less vulnerabilities

2023-08-30 22:00 UTC, amyleadem approved these changes
Confirming that `npm audit fix` reduces the number of vulnerabilities as described in the PR description.

- [x] Running `npm audit` on `develop` shows `33 vulnerabilities (4 moderate, 29 high)`
- [x] Running `npm audit fix` on `develop` shows `30 vulnerabilities (1 moderate, 29 high)`
- [x] `npm start` runs without error and the build looks as expected

2023-09-12 17:47 UTC, mejiaj requested changes
@mahoneycm can you fix conflicts? Otherwise LGTM.

2023-09-13 13:48 UTC, mahoneycm commented
@mejiaj Conflicts resolved 👍

2023-09-18 16:37 UTC, mejiaj approved these changes

2023-09-28 22:07 UTC, thisisdano approved these changes

2023-09-28 22:07 UTC, merged