USWDS - Button Group: Improve appearance of buttons with wrapping text
uswds/uswds pull request #5657
Opened 2023-12-05 19:51 UTC by mejiaj

# Summary

_Provide a one or two sentence summary of the update that can be used in the changelog._

## Breaking change

_Indicate if this update is a breaking change with **one** of the following statements:_
This is not a breaking change.
:warning: This is potentially a breaking change.
:warning: This is a breaking change.

## Related issue

Closes #_[issue_no]_

## Related pull requests

Extension of #5324.

This could include:
- New or updated component documentation,
- New or updated settings documentation, or
- Changelog entries.

Add links to any related PRs in this section. If this change requires an update
to the uswds-site repo, but that PR does not yet exist, just make sure to note that here.
-->

## Preview link

Preview link:

## Problem statement

_Summarize the problem this PR solves in a clear and concise statement._

## Solution

_Provide a summary of the solution this PR offers._

## Major changes

_For complex PRs, create a list of the significant updates made._

## Testing and review

_Share recommended methods for reviewing this change._

2023-12-06 15:41 UTC, mahoneycm requested changes
Looking good! I noticed a visual bug with anchor elements we should address. This should be good to go after that 👍

2023-12-06 17:26 UTC, amyleadem commented on packages/usa-button-group/src/styles/_usa-button-group.scss
Confirming that I see this issue in this PR. However, when I merged in the fixes from the `jm-enhancement-button-icons` branch, the issue appears to resolve itself. (I believe it is because the button icon branch adds `align-items: center` to `usa-button`.) 

I'll keep testing to be sure, but it appears as though no action will be needed to get this fixed in 3.7.1.

2023-12-06 18:00 UTC, mejiaj commented on packages/usa-button-group/src/styles/_usa-button-group.scss
Thanks @amyleadem, confirmed on my end too that `jm-enhancement-button-icons` fixes it. I'll update the description to note that.

2023-12-06 18:46 UTC, mejiaj commented on packages/usa-button-group/src/styles/_usa-button-group.scss
I've moved both issues to 3.8.0 to avoid unnecessary re-work.

2023-12-14 17:57 UTC, mejiaj commented on packages/usa-button-group/src/styles/_usa-button-group.scss
Resolving this thread as the issue outlined above is not part of the scope.

2023-12-14 17:58 UTC, mejiaj commented on packages/usa-button-group/src/styles/_usa-button-group.scss
@mahoneycm can you re-review considering the visual quirk outlined will be addressed in another issue?

2023-12-15 16:19 UTC, mahoneycm commented on packages/usa-button-group/src/styles/_usa-button-group.scss
Confirmed pulling in `jm-enhancement-button-icons` resolved the issue 👍

2023-12-15 16:20 UTC, mahoneycm approved these changes
- [x]  Button group maintains equal heights at various sizes
- [x]  Button group looks appropriate when one button has larger text content
- [x]  Previous inconsistencies are resolved
- [x]  No visual regressions

2024-01-03 15:32 UTC, amyleadem approved these changes
This is looking good. The `usa-button` elements inside the button group appear to be the same height regardless of their content, and the content is vertically centered. 

> [!IMPORTANT]
> My only note is that I'd like to mark this as a potentially breaking change since the default button group will no longer wrap at "desktop" widths. I think it would be helpful to warn users to check their implementations. 

## Tests

After pulling in `jm-enhancement-button-icons` from #5398, I confirmed the following in Chrome, Safari, and Firefox:

- [x] Confirm that all elements in a button group are the same height regardless of content height
- [x] Confirm that text is vertically centered inside the `usa-button` elements (in both regular and button group)
    - [x] Mobile view
    - [x] Desktop view
- [x] Confirm that icons are vertically centered inside button group elements
- [ ] Confirm that `nowrap` will not cause any unexpected breaks
- [x] Confirm that this works with both links and buttons

## Screenshots
### Mobile view
**Before (mobile)**
![image](https://github.com/uswds/uswds/assets/93996430/aa9dbf91-14f3-44a3-a62d-2f5699d0a8c1)

**After (mobile)**
![image](https://github.com/uswds/uswds/assets/93996430/e2f35e7e-7ae9-4316-95fa-07e6f421f782)

### Desktop view
**Before (desktop)**
![image](https://github.com/uswds/uswds/assets/93996430/ba097a83-c1ea-44a3-bc1e-81028e888b04)


**After (desktop)**
![image](https://github.com/uswds/uswds/assets/93996430/1a8c59c3-499a-4bf5-8a54-990e9aa6e1a4)

### With icons
I also tested this with icons (to confirm compatibility with #5398) and it worked as expected:

![image](https://github.com/uswds/uswds/assets/93996430/09d00593-ff99-4b40-8e28-15ab88352270)

![image](https://github.com/uswds/uswds/assets/93996430/9a385652-a26d-40e9-b246-529a508a35c4)

2024-01-03 15:39 UTC, amyleadem commented on packages/usa-button-group/src/styles/_usa-button-group.scss
Resolving this conversation after confirming that `jm-enhancement-button-icons` resolves this issue.

2024-01-03 15:41 UTC, mejiaj commented on packages/usa-button-group/src/styles/_usa-button-group.scss
Resolving this thread because issue is fixed by https://github.com/uswds/uswds/pull/5398.

2024-02-27 00:12 UTC, thisisdano approved these changes

2024-02-27 00:12 UTC, merged