USWDS - Dependencies: POAM Dec '23
uswds/uswds pull request #5673
Opened 2023-12-13 16:26 UTC by mejiaj

# Summary

_Provide a one or two sentence summary of the update that can be used in the changelog._

## Breaking change

_Indicate if this update is a breaking change with **one** of the following statements:_
This is not a breaking change.
:warning: This is potentially a breaking change.
:warning: This is a breaking change.

## Related issue

Closes #_[issue_no]_

## Related pull requests

_Indicate if there are other pull requests necessary to complete this issue._

## Preview link

Preview link:

## Problem statement

_Summarize the problem this PR solves in a clear and concise statement._

## Solution

_Provide a summary of the solution this PR offers._

## Major changes

_For complex PRs, create a list of the significant updates made._

## Testing and review

_Share recommended methods for reviewing this change._

2023-12-13 20:35 UTC, mahoneycm approved these changes
Lgtm!

- [x] Vulnerabilities reduced.
- [x] No build errors.
- [x] No other gulp task errors.
- [x] Style changers render in storybook correctly.
- [x] `npm audit fix` doesn't change any dependencies.

2023-12-13 20:35 UTC, mahoneycm commented on package.json
> -    "handlebars-helpers": "0.10.0",
Just flagging there's an [existing PR](https://github.com/uswds/uswds/pull/5599) to remove handlebars-helpers with some additional information. We can go ahead and close that PR in favor of this one 👍

2023-12-19 23:16 UTC, amyleadem requested changes
@mejiaj  I am getting an error here with the `gulp buildSass` command (as part of `npm run test`) that I am not seeing in `develop`. Are you seeing the same thing? 

Here is the error:
```
Error: Cannot find module 'sass'
Require stack:
- /Users/amy.leadem/Dev/github/workspace/uswds/node_modules/sass-true/lib/main.js
- /Users/amy.leadem/Dev/github/workspace/uswds/packages/uswds-core/src/test/sass.spec.js
- /Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/esm-utils.js
- /Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/mocha.js
- /Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/cli/one-and-dones.js
- /Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/cli/options.js
- /Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/bin/mocha
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.runSass (/Users/amy.leadem/Dev/github/workspace/uswds/node_modules/sass-true/lib/main.js:50:12)
    at Object.<anonymous> (/Users/amy.leadem/Dev/github/workspace/uswds/packages/uswds-core/src/test/sass.spec.js:6:10)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at exports.requireOrImport (/Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/esm-utils.js:42:12)
    at exports.loadFilesAsync (/Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at exports.handler (/Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/mocha/lib/cli/run.js:362:11)
    at /Users/amy.leadem/Dev/github/workspace/uswds/node_modules/gulp-mocha/node_modules/yargs/build/index.cjs:443:71
[16:13:42] 'sassTests' errored after 246 ms
[16:13:42] Error in plugin "gulp-mocha"
Message:
    There were test failures
Details:
    domainEmitter: [object Object]
    domainThrown: false

[16:13:42] 'test' errored after 7.37 s
```

2023-12-20 16:48 UTC, mejiaj commented
### re: gulp sassTests error

@amyleadem good find, I was able to reproduce. I've added two additional changes and updated the PR description.

1. Remove unreleased work related to `uswds-core` package [^1] [d09b1ab](https://github.com/uswds/uswds/pull/5673/commits/d09b1abf4511dde549365d377e8bf2087d0fed24).
2. Install `sass` dependency for `sass-true` [^2] [b478b7f](https://github.com/uswds/uswds/pull/5673/commits/b478b7f21f8ac9b50b8e9233d39bffbcc62b93d0).

[^1]: Once merged we can close out #5245.
[^2]: Not ideal, but I couldn't find any guidance in `sass-true` docs, issues, or pr's.

2024-01-19 16:45 UTC, amyleadem approved these changes
Thanks for fixing and thanks for the footnotes. 

- [x] Confirmed vulnerability changes listed in the PR description are current (44 vulnerabilities (17 moderate, 27 high))
- [x] Confirm dependency changes in the PR description match code changes
- [x] Run fresh `npm install` without error
- [x] Run `npm start`, `npm test`, `gulp`, and `npm run build:html` without error
- [x] Confirm Sass changes compile as expected

2024-02-27 00:15 UTC, thisisdano approved these changes

2024-02-27 00:15 UTC, merged