USWDS - In-Page Navigation: Fix scrolling to nested headers
uswds/uswds pull request #5878
Opened 2024-04-22 11:54 UTC by jhancock532

# Summary

**Fixed issue with in-page navigation being unable to scroll to nested headings.** The in-page navigation can now smooth scroll to headings within the summary box and card components.

## Breaking change

This is not a breaking change.

## Related issue

Closes #5255

## Related pull requests

_N/A_

## Preview link

Preview link:

## Problem statement

The in-page navigation should navigate the user to the section of the page with the indicated heading when the heading link is clicked. 

Currently, clicking on links that refer to nested headings, within the summary box or card components (or any other custom, non-standard USWDS component) causes the page to reset its scroll. 

This poor user experience hinders users from accessing content they are seeking quickly and may mislead users to thinking desired content doesn't exist on the page. Erroneous behaviour reduces users trust in the site and USWDS branded sites as a whole. 

## Solution

The existing code uses the `offsetTop` value of the element to identify how much to scroll down the page. This value is relative to the parent container. To correctly scroll to the location of the element, the `offsetTop` must be added to the `parentOffset` of all the elements parent components. This MR adds a function to calculate the elements true offset in this manner.

An alternative solution would be to refactor the code to use `scrollIntoView` instead. This would involve refactoring the approach we use to test this component, which is being supported using a mocked offsetTop value and watching the `window.scroll` function with `sinon`. 

## Major changes

No major changes to component implementation / testing approach made.

## Testing and review

A new Storybook story in the in-page navigation component has been created for testing. If running storybook locally, go to http://localhost:6006/iframe.html?args=&id=components-in-page-navigation--test-nested-headers&viewMode=story and click on each link in the in-page navigation. The page should correctly scroll to each heading in turn.

Any feedback on the solution would be helpful. I would like to add a test case to cover this fix, but I'm not sure how I'd go about mocking offsetParent only for certain elements. It also feels like if I was to mock this for specific contexts, the test would be verifying a very specific scenario instead of being representative. Using a testing framework such as Playwright instead of Jest would be helpful here.

2024-08-29 18:42 UTC, mahoneycm commented
Hey there @richard8, we have this slated to be a part of our `3.10.0` release. We're currently working on `3.9.0` to be released in the coming weeks and will be able to give this another look after that.

2024-11-20 21:08 UTC, mejiaj reviewed
Thanks for this submission, I was able to successfully test all variants in storybook comparing this with develop. Minor comment on const name, otherwise LGTM.

| Before | After |
| :----- | :---- |
| [Develop →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-in-page-navigation--default&p=all) |  [Feature →](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/jh-fix-in-page-navigation-scroll-bug/?path=/story/components-in-page-navigation--default)  |


### Additional testing

I've also created a testing branch on the website[^1] to verify this fixes the original bug. We'll have to communicate to users of `data-scroll-offset` to double-check the value and make sure there aren't regressions with this change.

### Things I tested

- [x] Unit tests pass
- [x] No regressions in existing variants
- [x] Fixes original bug

[^1]: uswds/uswds-site#2978

2024-11-20 21:11 UTC, mejiaj commented on packages/usa-in-page-navigation/src/index.js
> -    block: "start",
> [!NOTE]
> Removing `block` had no effect. Not seeing it as an option in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll) either.

2024-12-02 18:37 UTC, mahoneycm requested changes
This is looking great @jhancock532! Thank you so much for your contribution.

I left a couple questions and possible suggestions if you have the bandwidth. Excited to get this merged 👍

2024-12-02 18:37 UTC, mahoneycm commented on packages/usa-in-page-navigation/src/index.js
> +
**question:** Is the el.offsetParent && a truthy check to check for parent offset? If so, we might want to make the check a bit more human-readable to match existing USWDS patterns.

**suggestion:** Opt for `if` statement:

```suggestion
const getTotalElementOffset = (el) => {
  if (el.offsetParent) {
    return el.offsetTop +  getTotalElementOffset(el.offsetParent);
  } 

  return el.offsetTop
}
```

Curious if the rest of the team has another preference!

2024-12-02 18:37 UTC, mahoneycm commented on packages/usa-in-page-navigation/src/index.js
> + * @param {HTMLElement} el A heading element
**polish:** It looks like the `el` here is actually the anchor element if we want to specify

```suggestion
 * @param {HTMLAnchorElement} el - The link to the section heading.
```

2024-12-02 18:37 UTC, mahoneycm commented on packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
**Praise:** Thank you for creating this test story and following our naming conventions! This made it much easier to test.

2024-12-02 18:37 UTC, mahoneycm commented on packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
**question:** Would you have the bandwidth to create a unit test for this work as well? If not, let us know so we can coordinate making one! Thanks!

2024-12-02 18:37 UTC, mahoneycm commented on packages/usa-in-page-navigation/src/index.js
> [!IMPORTANT]
> We'll need to update the header offset logic on our website to account for this change.
>
> Installing this branch on Site did resolve the bug where nested headers would cause the window to scroll to the top of the page but due to our custom JS the offset was not calculated correctly.

2024-12-03 22:13 UTC, mejiaj commented on packages/usa-in-page-navigation/src/index.js
Good point. Noted in https://github.com/uswds/uswds-site/pull/2978#discussion_r1850942384.

2024-12-04 10:19 UTC, jhancock532 commented on packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
Hello, thank you for the review. I'll be able to look into this and make fixes from the 10th of December, when our new sprint of work starts (hopefully that's not too much of a delay). 

I can try my best at creating a unit test to cover this behavior, if you have any suggestions on how to approach this it would be much appreciated. I left a comment at the bottom of the MR description wondering how we'd handle mocking the `offsetParent` value when using Jest - there might be another way of handling this that I've not thought of, or a more creative solution to test the same behavior.

2024-12-18 13:49 UTC, jhancock532 commented on packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
Unfortunately other work has come up and this has been pushed back until some point in the new year, I can leave another comment when I find out more - if this is a risk of being a blocker then others can make changes to this MR as well

2024-12-18 16:14 UTC, mahoneycm commented on packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
Thank you for the heads up! I moved the issue to `in progress` and added the `triage` label so that this stays on our radar. If we take over next steps, we'll let you know.

I appreciate the contributed work and communication!

2025-01-08 19:12 UTC, mgwalker commented
I believe this also fixes #6295.

2025-01-09 15:36 UTC, mejiaj commented on packages/usa-in-page-navigation/src/index.js
> +  const offsetTop = getTotalElementOffset(el);
Fixed in 3be1ceac7.

2025-01-09 15:37 UTC, mejiaj commented on packages/usa-in-page-navigation/src/index.js
> + * @param {HTMLElement} el A heading element
Fixed in 3be1ceac7.

2025-01-10 21:49 UTC, mahoneycm commented on packages/usa-in-page-navigation/src/test/test-patterns/test-nested-headers.twig
Hey there @jhancock532! 

I took a stab at creating the unit test. It pointed out some shortcomings in our current unit test for in-page nav. For the time being, I don't think this needs to be a blocker for the work.

Thank you for your contribution! I'm going to approve and hope we can improve our testing as a future enhancement.

2025-01-10 22:04 UTC, mahoneycm submitted a review, later dismissed
Feature is working great! Great enhancement to the in-page navigation.

**Limitations of unit testing**

Since `jsdom` doesn't emulate positions, our unit tests are limited to feining offset based on how many elements are on the page. We should look into improving these tests in the future but I don't believe it should be a blocker for this work 👍

2025-01-13 14:58 UTC, mejiaj submitted a review, later dismissed
Thanks for contributing!

There is some awkwardness when clicking on headers in our test pages because of the lack of content. Especially when clicking on nested headings, but this behavior can also be seen on [develop](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-in-page-navigation--default&p=all).

### Follow-up changes

1. **Mark as potentially breaking.** We should also make this as a `potentially breaking change` and suggest to users to revisit their implementation if they've modified `data-scroll-offset` (like we did in site). 
2. **Update implementation on site.** We should follow instructions [here](https://github.com/uswds/uswds-site/pull/2978#discussion_r1850942384) to update the implementation on site.
3. **Explore ways to improve our testing.** Our tests could include more content and our unit tests could use a spike to explore ways to more reliably test this component.

2025-01-17 15:36 UTC, mahoneycm commented
@jhancock532 , thank you for this contribution!

For security reasons, USWDS requires that all commits to this repo have a verified signature. Your commits are registering as unverified, so we will need you to complete the following steps before this contribution can be merged:
1. **Set up signature verification in GitHub.** Use one of the following GitHub guides to set up your verification signature:
    - [GPG commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification) 
    - [SSH commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification)
1. **Rebase your commits with your verified signature.** Once your signature is set up, complete the following steps in the terminal to update the verification status of your previous commits:

    ```
    git checkout branch-name
    git rebase origin/develop
    git push --force-with-lease
    ```

Please let us know if you have any questions.

2025-01-23 15:05 UTC, jhancock532 commented
Hello @mahoneycm, I'm having some difficulty rebasing with signed commits, I might be going about it the wrong way. 

Following the above instructions locally, there are then 1809 rebase steps, and the `package-lock.json` file is flagging as a conflict to be resolved from step 5 onwards (this file appears to cause a rebase conflict every few steps or so, I'm not sure why though - something to do with merging in develop?). 

Does it make sense for me to create a new MR with verified commits for the changes, as this MR has been flagged for more code review anyway? The failing pipeline seems to be an unrelated issue with the date-picker component which shouldn't be affected by this MR.

2025-01-23 16:49 UTC, mahoneycm commented
@jhancock532 thanks for reaching out! I'm going to see if I can rebase this for you with verified commits. If all goes well, we should be able to avoid you having to create a new PR 👍

2025-01-28 16:26 UTC, heymatthenry approved these changes
Woohoo! Thanks, @jhancock532 and team!

2025-01-28 16:26 UTC, merged