USWDS - POAM: May '24
uswds/uswds pull request #5924
Opened 2024-05-10 20:44 UTC by mahoneycm

# Changelog PR

**Title**

USWDS - POAM: May ‘24

# Summary

POAM updates for May 2024

> [!IMPORTANT]
This work should be merged after the April POAM updates #5854
> 

## Breaking change

This is not a breaking change.

## Preview link

Preview link →

## Major changes

Minor and patch updates to direct dependencies

## Testing and review

1. Run `npm install` and confirm there are no errors
2. Run `npm start`.
3. Update a SASS file and see it update in StorybookJS.
4. Running `npx gulp sassTests` or `npm run test` should **not** fail.
5. Run gulp tasks (like build) and ensure there aren't errors and things build correctly
6. Installing on site does not cause any installation or build errors

## Dependency updates

| Dependency name | Previous version | New version |
| --- | --- | --- |
| @babel/core | 7.23.4 | 7.23.5 |
| @babel/preset-env | 7.24.4 | 7.24.5 |
| @types/node | 20.12.5 | 20.12.11 |
| axe-core | 4.9.0 | 4.9.1 |
| post-css-preset-env | 9.5.4 | 9.5.11 |
| sass | 1.74.1 | 1.77.0 |
| sass-embedded | 1.74.1 | 1.77.0 |
| snyk | 1.1287.0 | 1.1291.0 |
| svgo | 3.2.0 | 3.3.2 |
| typescript | 5.4.4 | 5.4.5 |

2024-05-20 17:02 UTC, mejiaj requested changes
We'll need to update once #5854 and #5782 are merged.

2024-05-24 14:28 UTC, mejiaj approved these changes
**Before** [`develop`]
```
43 vulnerabilities (13 moderate, 30 high)
```

**After**
```
41 vulnerabilities (13 moderate, 28 high)
```

Did a quick check on styles in storybook and I don't see any visual regressions either.

2024-05-24 14:32 UTC, amyleadem approved these changes
LGTM!
- [x] Ran `npm install`, `npm run start`, `npm run build`, and `npm run test` without error
- [x] Updated styles and confirmed they were reflected in storybook
- [x] Confirmed the dependency list in the PR description matches the changed dependencies.

2024-05-28 21:39 UTC, thisisdano approved these changes

2024-05-28 21:39 UTC, merged