USWDS - Memorable Date: Remove numbers from the dropdown list of months
uswds/uswds pull request #6028
Opened 2024-08-19 18:10 UTC by cathybaptista

# Summary

**Removed the leading numbers from the month options in the memorable date component.** Recent usability testing indicated that having both numbers and names to represent months was confusing for screen reader users.

## Breaking change

This is not a breaking change.

## Related issue

Closes https://github.com/uswds/uswds/issues/5910

## Related pull requests

Changelog uswds/uswds-site#2787

## Preview link

Preview link: [Memorable Date preview
](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cb-memorable-date-input-options/?path=/story/components-form-inputs-memorable-date--memorable-date)

## Problem statement

The desired state for the memorable date component is that there is only one option for the values in the months dropdown (either numbers or month names) so that users can search by typing in the month name. The current state is that both the number and the month name are included in the option dropdown, which means users cannot search by the month name. 

## Solution

The solution is to remove the numbers from the memorable date component option dropdown. Another approach was to make both options (numbers AND month names) available, but the risk of this approach did not outweigh the rewards. The team decided that including month names is the best way to resolve this accessibility issue. 

## Testing and review

1. Opened federalist link and inspected source.
2. Verify that the id="date_of_birth_month" options do not include a number.
3. Opened the component in production.
4. Verify that the id="date_of_birth_month" options includes a number.
5. Verify that if you tab to the memorable date month field and hit the first letter of each month on the keyboard the correct month appears.
6. Verify that the correct code appears on uswds-site for this component when the "component code" button is selected. This code should not include numbers.

2024-08-23 20:36 UTC, mejiaj approved these changes
Confirming I can navigate using keyboard more easily. Thanks Cathy!

[uswds-memorable-date-6028.webm](https://github.com/user-attachments/assets/c13ea62d-c670-4d9f-8c5a-8dcb4467a223)

2024-08-23 21:08 UTC, mahoneycm approved these changes
Searching by name is working for me! I think this will clear up a lot of the confusion.

Thanks @cathybaptista !

2024-08-26 18:42 UTC, amyleadem requested changes
Thanks for making this update @cathybaptista. The code update looks good!

Quick request before approval: Can you update the summary in the PR description to be a bit more succinct? We try to pull that PR summary into the release notes and the current one is a bit too long to be useful in that context. If desired, we can move the additional information that is currently in the "summary" section down to the "solution" section. 

I'm thinking something like this should work (Feel free to edit):

**Removed the leading numbers from the month options in the memorable date component.** Recent usability testing indicated that having both numbers and names to represent months was confusing for screen reader users.

2024-08-28 14:26 UTC, mejiaj commented
Moving the original issue back to `In progress` to capture requested changes @amyleadem mentioned.

2024-08-28 18:29 UTC, amyleadem approved these changes
Looks good to me! Thanks @cathybaptista 

Moved the issue to FFR

2024-10-03 03:39 UTC, thisisdano approved these changes

2024-10-03 03:40 UTC, merged