USWDS - Radio and checkbox: Update label width to fit content
uswds/uswds pull request #6192
Opened 2024-11-08 19:50 UTC by cathybaptista

# Summary

Changed display for radio buttons and checkbox to inline-block so that label fits its content. Added inherit to display for tile variant.

## Breaking change

This is not a breaking change.

## Related issue

Closes #6111 

## Related pull requests

[Changelog](https://github.com/uswds/uswds-site/pull/2961)

## Preview link

[Preview link radios:](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cb-tighten-selectable-whitespace-in-radios/?path=/story/components-form-inputs-radio--default)

[Preview link checkboxes:](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/cb-tighten-selectable-whitespace-in-radios/?path=/story/components-form-inputs-checkbox--default)

## Problem statement

The selectable area adjacent to radio buttons and checkboxes was full width. This resulted in being able to select the button from an area far away from the component. This fix tightens the selectable area around these components.

### NOTE

This issue also impacts checkbox. The same solution should apply to both components.

## Solution

With display: block, the radio button's label occupies the full width of its parent container. With display: inline-block, the label will only occupy the space needed to fit its content.

## Testing and review

1. Open the federalist link for radios.
2. Verify that each radio button item under form inputs is only actionable directly over the button.
3. Open the federalist link for checkboxes.
4. Verify that each checkbox item under form inputs is only actionable directly over the button.
5. Check for regressions, especially that in tiled variant the right margin is not ragged.

Before opening this PR, make sure you’ve done whichever of these applies to you:
- [x] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `develop`).
- [x] Run `npm run prettier:sass` to format any Sass updates.
- [x] Run `npm test` and confirm that all tests pass.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.

2024-11-18 16:42 UTC, mahoneycm requested changes
**Issue (blocking):** This causes a visual regression for the tile variants. 

| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/205ff941-cb14-4a65-a502-bf264a0bc201) | ![image](https://github.com/user-attachments/assets/6905d0a3-e682-4867-95ec-9c502013c68d) | 

It looks like we'll want to maintain the `block` display in tile variants to prevent this regression.

2025-01-03 20:37 UTC, mahoneycm approved these changes
LGTM! Thanks Cathy!

- [x] No visual regressions
- [x] Standard radio/checkbox cannot be triggered via whitespace
- [x] Tile variants can be activated on their tile
- [x] Styles make sense and are necessary for proper display

2025-01-03 21:55 UTC, amyleadem approved these changes
LGTM! Thanks @cathybaptista

I completed the following checks in Firefox, Safari, and Chromium:
- [x] Confirm the interaction area for both radio and checkboxes do not expand beyond the label content in default variant
    - ![image](https://github.com/user-attachments/assets/2734dbd3-b605-4a62-b839-2021d051881d)
    - ![image](https://github.com/user-attachments/assets/5e9eedfc-7e4f-437c-83d5-1e505698f935)
- [x] Confirm the interaction area for both radio and checkboxes fills the entire bordered area in the tile variant
- [x] Confirm there are no visual regressions in any of the component variants
- [x] Confirm that the checkboxes and radio buttons can still be interacted with as expected with both keyboard and mouse.
- [x] Confirm the code changes make sense and meet USWDS standards
- [x] Confirm the PR description is up-to-date and accurate

2025-01-22 22:30 UTC, thisisdano approved these changes
Does what it says on the tin! Nice change

2025-01-22 22:30 UTC, merged