Cm error story margin addl
uswds/uswds pull request #6230
Opened 2024-11-27 20:58 UTC by mahoneycm

# Summary

Adds horizontal margin to stories that feature an error state component in order to display form group error border if present.

## Breaking change

This is _not_ a breaking change.

## Related pull requests

Additional work to potentially be included in #6204

## Preview link

## Problem statement

Form group error borders are pushed off screen and are hidden.

## Solution

Add horizontal margin to storybook previews featuring error states

## Testing and review

1. Visit each of the error state previews above
2. Confirm we want to add the margin decorator to each of the examples.

2024-11-29 22:59 UTC, amyleadem requested changes
Thanks for this @mahoneycm. I like the idea of adding the padding to these components. I don't think this should be a blocker for #6204, but I think it would be a good addition if we can make it. I added a suggestion below to elevate the location of the decorators to add them at either the global or component level. Let me know if you have any questions.

2024-11-29 22:59 UTC, amyleadem commented on packages/usa-character-count/src/usa-character-count.stories.js
**suggestion:** Move this decorator to the story level so that you only need to add it once to the file. [^1]

Alternatively, I wonder if there is any value (or harm) to setting this at the global level in preview.js. That would prevent us from needing to remember this decorator for every component. 

```diff
export default {
  title: "Components/Form Inputs/Character Count",
+  decorators: [
+    (Story) =>
+      `<div class="padding-x-205">
+        ${Story()}
+      </div>`,
+  ],
  argTypes: {
    disabled_state: {
      name: "Disabled state",
      control: { type: "radio" },
      options: ["none", "disabled", "aria-disabled"],
    },
  },
};
```
[^1]: https://storybook.js.org/docs/writing-stories/decorators

2024-12-02 14:58 UTC, mahoneycm commented on packages/usa-character-count/src/usa-character-count.stories.js
I was wondering if we could take a similar approach to updating some base styles similar to how we do in the [web components repo](https://github.com/uswds/web-components/blob/develop/storybook/index.css). I feel like globally adding a bit of margin so that the component previews are all uniform might be the better idea 🧐

2024-12-03 20:59 UTC, mejiaj commented on packages/usa-character-count/src/usa-character-count.stories.js
I don't see any harm in increasing padding, but could also see it as a follow-up enhancement.

2026-09-11 01:59 UTC, opensource-joe commented
This isn't tied to an open issue and #6204, the PR it was supplementary to, already merged in December 2024, so nothing is blocked on it. All three reviewers landed on the same point though: the padding is worth having, but a per-story decorator is the wrong place for it. Amy suggested component-level or global preview.js, and Charlie separately pointed at the same pattern already used in the web-components repo's Storybook config. That's a small rework, not a rejection, just never got picked back up.

2026-09-14 20:18 UTC, ryparker commented
Closing this as part of a backlog cleanup, and I want to be accurate about why.

This PR never got a review. It wasn't rejected and nobody found a problem with it — you opened it, and we didn't respond. That's on us, and I'm sorry it sat this long.

I'm closing it because the review queue is longer than the team can work through, not because the change was wrong. If you still want it in, comment here and I'll pick it up with you, including the rebase — I'm not going to ask you to redo unpaid work to get back to where you already were. You can also reopen this yourself.

Thanks for the contribution, and sorry for the silence.

2026-09-14 20:18 UTC, closed without merging