USWDS - README: fixed some deadlinks in the README for design system inspirations
uswds/uswds pull request #6239
Opened 2024-12-04 21:52 UTC by jcklpe

# Summary

I noticed that some links in the README were dead so I replaced them with what I believe are the proper up to date links. I also changed the wording of the US Patent Office Design Patterns to "Design System" since the website for it says that. 

## Breaking change
No breaking changes. 

## Related issue

Closes #_[issue_no]_
I don't think this closes anything. 

## Related pull requests
None

## Preview link
None

## Problem statement
No deadlinks in the README. (I know this is a small thing, but thought it would be helpful. I'm looking to get more involved in helping contribute directly)

## Solution
Updated the links with the latest versions of those design systems. 

## Major changes
none

## Testing and review
Just check the README file and scroll to the bottom section where it lists out design system inspirations.

2024-12-23 21:57 UTC, annepetersen approved these changes
LGTM. Thanks for the contribution, and welcome! Hope to see more from you in the future. (and thanks for your patience)

2024-12-30 23:32 UTC, jcklpe commented
@annepetersen Hi it looks like merging is blocked, and I think it might be on my end:  
  
 

![](https://github.com/user-attachments/assets/1527e552-f3fe-44d8-821a-d3326295b04c)

I'm not really a dev, just a designer who sticks their nose into github too much haha. Is this a problem that I need to fix on my end?

2025-01-02 22:36 UTC, amyleadem requested changes
Thanks for this contribution @jcklpe. I added one suggestion in the comments below. Both urls point to the correct project, but one is more similar to the original link. Please let me know if you have any questions.

2025-01-02 22:36 UTC, amyleadem commented on README.md
> +- Pivotal Labs [Component Library](https://github.com/pivotal-cf/pivotal-ui)
**suggestion:** This new url points directly to the GitHub repo, whereas before it pointed to the documentation website ([Previous link from the Wayback machine](https://web.archive.org/web/20200203095306/http://styleguide.cfapps.io/)). It looks like they still have an [active documentation website for the library](https://pivotal-cf.github.io/pivotal-ui/). I recommend pointing to that instead: 

```suggestion
- Pivotal Labs [Component Library](https://pivotal-cf.github.io/pivotal-ui/)
```

2025-01-02 22:36 UTC, amyleadem commented on README.md
> +- U.S. Patent and Trademark Office’s [Design System](https://uspto.github.io/USPTO-Design-System/)
> [!note]
> Confirming that this appears to be an appropriate replacement. This original url pointed to v1 of the USPTO site, whereas the new url points to v2:
> 
> [Before](https://web.archive.org/web/20240512152552/https://uspto.github.io/designpatterns/) | [After](https://uspto.github.io/USPTO-Design-System/)

2025-01-06 16:26 UTC, amyleadem approved these changes

2025-01-06 19:36 UTC, jcklpe commented on README.md
> +- U.S. Patent and Trademark Office’s [Design System](https://uspto.github.io/USPTO-Design-System/)
Yes this looks good to me!

2025-01-07 19:57 UTC, amyleadem commented
@jcklpe, 
For security reasons, USWDS now requires that all commits to this repo have a verified signature. Your commits are registering as unverified, so we will need you to complete the following steps before this contribution can be merged:
1. **Set up signature verification in GitHub.** Use one of the following GitHub guides to set up your verification signature:
    - [GPG commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification) 
    - [SSH commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification)
1. **Rebase your commits with your verified signature.** Once your signature is set up, complete the following steps in the terminal to update the verification status of your previous commits:

    ```
    git checkout branch-name
    git rebase origin/main
    git push --force-with-lease
    ```
Thanks again for your contribution. Please let us know if you have any questions or if we can help in any way.

2025-01-08 21:42 UTC, jcklpe commented
> @jcklpe, For security reasons, USWDS now requires that all commits to this repo have a verified signature. Your commits are registering as unverified, so we will need you to complete the following steps before this contribution can be merged:
> 
> 1. **Set up signature verification in GitHub.** Use one of the following GitHub guides to set up your verification signature:
>    
>    * [GPG commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)
>    * [SSH commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification)
> 2. **Rebase your commits with your verified signature.** Once your signature is set up, complete the following steps in the terminal to update the verification status of your previous commits:
>    ```
>    git checkout branch-name
>    git rebase origin/main
>    git push --force-with-lease
>    ```
> 
> Thanks again for your contribution. Please let us know if you have any questions or if we can help in any way.

Apologies for my inexpertise. I have GPG set up, but am having a little trouble with the git rebasing. 

```
└─➤ git rebase origin/fix-README-deadlinks                                                                                                                                   fix-README-deadlinks  
Current branch fix-README-deadlinks is up to date.
```
I did rebase origin/fix-README-deadlinks since origin/main didn't work (USWDS uses a develop branch instead of main, right?) and I figured from the origin/main error that meant I should rebase to the specific branch that I was working on but that didn't seem to turn out. 

I also tried making additional changes (as per feedback given up thread), and make another commit. But despite making another commit and pushing it to github, I don't see those changes in my github hosted fork, or it updating the pull request.

2025-01-10 18:49 UTC, amyleadem commented
@jcklpe Does it work if you run `git rebase origin/develop` in place of `git rebase origin/main`?

2025-01-10 18:52 UTC, jcklpe commented
> @jcklpe Does it work if you run `git rebase origin/develop` in place of `git rebase origin/main`?

```
┌─   ~/work/uswds                                                                                                                                                                              
└─➤ git rebase origin/develop                                                                                                                                                
Current branch fix-README-deadlinks is up to date.
```

Doesn't look like it.

2025-01-16 18:38 UTC, mahoneycm commented
@jcklpe  does running `git fetch` before `git rebase origin/develop` to fetch upstream changes help?

I checked out this PR and was able to rebase successfully, likely because I already had the latest changes from `develop`.

2025-01-22 22:12 UTC, thisisdano submitted a review, later dismissed

2025-01-22 22:49 UTC, jcklpe commented
> does running `git fetch` before `git rebase origin/develop` to fetch upstream changes help?
> 
> I checked out this PR and was able to rebase successfully, likely because I already had the latest changes from `develop`.
It does not appear to. 

```
┌─     ~/work/uswds                                                                                                                            
└─➤ git fetch                                                                                                              fix-README-deadlinks   

┌─     ~/work/uswds                                                                                                                            
└─➤ git rebase origin/develop                                                                                              fix-README-deadlinks   
Current branch fix-README-deadlinks is up to date.

```

2025-01-31 22:03 UTC, thisisdano approved these changes

2025-01-31 22:20 UTC, merged